package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/agenticode/kilter/pkg/domain"
	kebs "github.com/agenticode/kilter/pkg/ebs"
	kec2 "github.com/agenticode/kilter/pkg/ec2"
	kecs "github.com/agenticode/kilter/pkg/ecs"
	klambda "github.com/agenticode/kilter/pkg/lambda"
	"github.com/agenticode/kilter/pkg/model"
	kcommit "github.com/agenticode/kilter/pkg/pricing/commit"
)

// The integration tests below drive the real domain packages through the real
// CLI layer over RECORDED SNAPSHOTS in testdata/. Nothing here opens a socket,
// links an AWS SDK, or reads a clock: fixtureNow is the decision time
// everywhere, and every snapshot's timestamps are derived from it.
//
// The fixtures are generated by this file rather than hand-written JSON,
// because a hand-written 14-day 5-minute metric series is four thousand
// objects nobody will ever review. Regenerate with:
//
//	go test ./cmd/kilter -run TestWriteDomainFixtures -update-fixtures
//
// and commit the result. The generator is deterministic — same inputs, same
// bytes — so a regeneration that changes a file is a change in a domain
// package's collector, which is exactly when a reviewer should look.

var updateFixtures = flag.Bool("update-fixtures", false,
	"regenerate cmd/kilter/testdata domain snapshots")

// fixtureNow is the single decision time for every fixture and every test that
// reads one. It is a constant so a test can assert exact dollars.
var fixtureNow = time.Date(2026, 8, 26, 12, 0, 0, 0, time.UTC)

const (
	fixtureScope   = "000000000000/us-east-1"
	fixtureRegion  = "us-east-1"
	fixtureCluster = "prod"
)

func fixturePath(name string) string { return filepath.Join("testdata", name) }

// TestWriteDomainFixtures regenerates testdata/ when -update-fixtures is
// passed, and otherwise asserts that the committed fixtures still match what
// the generator produces. That second half is the point: it turns the
// fixtures into a contract test on the collectors that built them.
func TestWriteDomainFixtures(t *testing.T) {
	for _, f := range []struct {
		name  string
		build func(*testing.T) any
	}{
		{"ec2-instances.json", func(t *testing.T) any { return buildInstanceSnapshot(t) }},
		{"ec2-volumes.json", func(t *testing.T) any { return buildVolumeSnapshot(t) }},
		{"ecs-services.json", func(t *testing.T) any { return buildECSSnapshot(t) }},
		{"lambda-functions.json", func(t *testing.T) any { return buildLambdaSnapshot(t) }},
		{"commitments.json", func(t *testing.T) any { return buildInventory() }},
		{"cluster.json", func(t *testing.T) any { return buildClusterSnapshot() }},
	} {
		t.Run(f.name, func(t *testing.T) {
			want, err := json.Marshal(f.build(t))
			if err != nil {
				t.Fatalf("marshal: %v", err)
			}
			want = append(want, '\n')
			path := fixturePath(f.name)
			if *updateFixtures {
				if err := os.MkdirAll("testdata", 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, want, 0o644); err != nil {
					t.Fatal(err)
				}
				return
			}
			got, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("%v (run with -update-fixtures to create it)", err)
			}
			if string(got) != string(want) {
				t.Errorf("%s is stale: the generator no longer reproduces it.\n"+
					"Regenerate with -update-fixtures and review the diff — a change here "+
					"means a domain package's collector changed.", path)
			}
		})
	}
}

// buildInstanceSnapshot records a four-instance EC2 account through pkg/ec2's
// real collector, and wraps the result in the generic envelope's Payload.
//
// The four instances are chosen so the report exercises every arm of the
// engine at once:
//
//	i-…a  m5.2xlarge, over-provisioned, WITH a memory signal   → a real proposal
//	i-…b  r5.xlarge,  over-provisioned, NO memory signal       → memory-blind refusal
//	i-…c  t3.large,   idle but credit-depleted                 → burst refusal
//	i-…d  c5.large,   tagged as a Kubernetes node              → k8s-tagged refusal
//
// i-…a is the ONLY m5 in the account, which is what makes the commitment
// fixture bite: a size-flexible m5 reservation with a second m5 to land on
// would simply move its discount there, and the saving would be real.
func buildInstanceSnapshot(t *testing.T) *domain.Snapshot {
	t.Helper()
	const period = 5 * time.Minute
	const points = 2304 // 8 days of 5-minute datapoints

	fix := &kec2.Fixture{
		InventoryPages: []kec2.DescribeInstancesOutput{{
			Reservations: []kec2.Reservation{{
				ReservationID: "r-fixture",
				Instances: []kec2.InstanceRecord{
					{
						InstanceID: "i-0000000000000000a", InstanceType: "m5.2xlarge",
						Architecture: "x86_64", Tenancy: "default", State: "running",
						AvailabilityZone: fixtureRegion + "a", MonitoringState: "disabled",
						LaunchTime: fixtureNow.Add(-90 * 24 * time.Hour),
						Tags:       []kec2.Tag{{Key: "Name", Value: "report-renderer"}},
					},
					{
						InstanceID: "i-0000000000000000b", InstanceType: "r5.xlarge",
						Architecture: "x86_64", Tenancy: "default", State: "running",
						AvailabilityZone: fixtureRegion + "a", MonitoringState: "disabled",
						LaunchTime: fixtureNow.Add(-90 * 24 * time.Hour),
						Tags:       []kec2.Tag{{Key: "Name", Value: "search-indexer"}},
					},
					{
						InstanceID: "i-0000000000000000c", InstanceType: "t3.large",
						Architecture: "x86_64", Tenancy: "default", State: "running",
						AvailabilityZone: fixtureRegion + "b", MonitoringState: "disabled",
						CPUCredits: kec2.CreditModeStandard,
						LaunchTime: fixtureNow.Add(-90 * 24 * time.Hour),
						Tags:       []kec2.Tag{{Key: "Name", Value: "cron-runner"}},
					},
					{
						InstanceID: "i-0000000000000000d", InstanceType: "c5.large",
						Architecture: "x86_64", Tenancy: "default", State: "running",
						AvailabilityZone: fixtureRegion + "b", MonitoringState: "disabled",
						LaunchTime: fixtureNow.Add(-90 * 24 * time.Hour),
						Tags: []kec2.Tag{
							{Key: "Name", Value: "eks-node"},
							{Key: "kubernetes.io/cluster/prod", Value: "owned"},
						},
					},
				},
			}},
		}},
		Metrics: []kec2.RecordedSeries{
			// a: ~8 % CPU, ~18 % memory. Both signals present, so the sizer
			// may propose a smaller shape in BOTH dimensions.
			kec2.SyntheticSeries("i-0000000000000000a", kec2.MetricCPUUtilization,
				fixtureNow, period, points, []float64{7, 8, 9, 8}),
			kec2.SyntheticSeries("i-0000000000000000a", kec2.MetricMemUsedPercent,
				fixtureNow, period, points, []float64{17, 18, 19, 18}),
			// b: same idleness, no memory series at all — CloudWatch's default
			// for an instance with no agent. The memory floor becomes the
			// instance's current memory (§7 trap 4).
			kec2.SyntheticSeries("i-0000000000000000b", kec2.MetricCPUUtilization,
				fixtureNow, period, points, []float64{6, 7, 8, 7}),
			// c: idle-looking, but the credit balance is on the floor. The low
			// CPU is a ceiling AWS imposed, not demand (§7 trap 5).
			kec2.SyntheticSeries("i-0000000000000000c", kec2.MetricCPUUtilization,
				fixtureNow, period, points, []float64{29, 30, 31, 30}),
			kec2.SyntheticSeries("i-0000000000000000c", kec2.MetricCPUCreditBalance,
				fixtureNow, period, points, []float64{0, 0, 1, 0}),
			// d: a cluster node. Sized by the k8s-nodes pipeline, never here.
			kec2.SyntheticSeries("i-0000000000000000d", kec2.MetricCPUUtilization,
				fixtureNow, period, points, []float64{40, 45, 50, 45}),
		},
	}

	col, err := kec2.NewCollector(fix, fix, kec2.CollectorConfig{
		Scope: fixtureScope, Region: fixtureRegion,
		Window: 8 * 24 * time.Hour, CollectMemory: true,
	})
	if err != nil {
		t.Fatalf("ec2 collector: %v", err)
	}
	snap, err := col.Collect(context.Background(), fixtureNow)
	if err != nil {
		t.Fatalf("ec2 collect: %v", err)
	}
	return wrapPayload(t, domain.EC2, fixtureScope, snap)
}

// buildVolumeSnapshot records a three-volume EBS account through pkg/ebs's
// real collector. The generic envelope carries these as Targets and Samples —
// no Payload — because that is what pkg/ebs's own collector emits, and the
// integration test is worth more if it exercises the shipped path.
//
//	vol-…1  200 GiB gp2, lightly used   → gp2→gp3 conversion
//	vol-…2  350 GiB gp2                 → the 334-375 GiB parity REFUSAL band
//	vol-…3  100 GiB gp3                 → not-gp2 refusal
func buildVolumeSnapshot(t *testing.T) *domain.Snapshot {
	t.Helper()
	// 15-minute spacing over the 7-day window. Coverage is deliberately below
	// Config.MinCoverage, which is the interesting case: the proposal is then
	// FLOORED at gp2's delivered baseline rather than sized to measured
	// demand, so a thin observation can only ever produce a same-or-better
	// volume (pkg/ebs/FINDINGS.md §2, the floor rule).
	const period = 15 * time.Minute
	const points = 672

	vols := []kebs.VolumeRecord{
		{
			VolumeID: "vol-00000000000000001", VolumeType: kebs.VolumeTypeGP2,
			SizeGiB: 200, IOPS: 600, State: kebs.VolumeStateInUse,
			AvailabilityZone: fixtureRegion + "a",
			CreateTime:       fixtureNow.Add(-200 * 24 * time.Hour),
			Attachments: []kebs.VolumeAttachment{{
				InstanceID: "i-0000000000000000a", State: kebs.AttachmentAttached,
			}},
			Tags: []kebs.Tag{{Key: "Name", Value: "reports-data"}},
		},
		{
			VolumeID: "vol-00000000000000002", VolumeType: kebs.VolumeTypeGP2,
			SizeGiB: 350, IOPS: 1050, State: kebs.VolumeStateInUse,
			AvailabilityZone: fixtureRegion + "a",
			CreateTime:       fixtureNow.Add(-200 * 24 * time.Hour),
			Attachments: []kebs.VolumeAttachment{{
				InstanceID: "i-0000000000000000b", State: kebs.AttachmentAttached,
			}},
			Tags: []kebs.Tag{{Key: "Name", Value: "index-scratch"}},
		},
		{
			VolumeID: "vol-00000000000000003", VolumeType: kebs.VolumeTypeGP3,
			SizeGiB: 100, IOPS: 3000, ThroughputMBps: 125, State: kebs.VolumeStateInUse,
			AvailabilityZone: fixtureRegion + "b",
			CreateTime:       fixtureNow.Add(-30 * 24 * time.Hour),
			Tags:             []kebs.Tag{{Key: "Name", Value: "already-gp3"}},
		},
	}

	fix := &kebs.Fixture{
		InventoryPages: []kebs.DescribeVolumesOutput{{Volumes: vols}},
		Now:            func() time.Time { return fixtureNow },
	}
	// CloudWatch reports EBS ops as a Sum over the period, so the values below
	// are per-5-minute counts: 300 s × the IOPS we want to look like.
	for _, id := range []string{"vol-00000000000000001", "vol-00000000000000002"} {
		fix.Metrics = append(fix.Metrics,
			ebsSeries(id, kebs.MetricVolumeReadOps, period, points, 300*20),
			ebsSeries(id, kebs.MetricVolumeWriteOps, period, points, 300*25),
			ebsSeries(id, kebs.MetricVolumeReadBytes, period, points, 300*2*kebs.MiB),
			ebsSeries(id, kebs.MetricVolumeWriteBytes, period, points, 300*3*kebs.MiB),
		)
	}

	col, err := kebs.NewCollector(fix, fix, kebs.CollectorConfig{
		Scope: fixtureScope, Region: fixtureRegion, Window: 7 * 24 * time.Hour,
	})
	if err != nil {
		t.Fatalf("ebs collector: %v", err)
	}
	snap, err := col.Collect(context.Background(), fixtureNow)
	if err != nil {
		t.Fatalf("ebs collect: %v", err)
	}
	return snap
}

func ebsSeries(volumeID, metric string, period time.Duration, n int, value float64) kebs.RecordedSeries {
	pts := make([]kebs.Point, n)
	start := fixtureNow.Add(-time.Duration(n) * period)
	for i := range pts {
		pts[i] = kebs.Point{At: start.Add(time.Duration(i+1) * period), Value: value}
	}
	return kebs.RecordedSeries{VolumeID: volumeID, Metric: metric, Points: pts}
}

// buildECSSnapshot records two ECS Fargate services. pkg/ecs has no fixture
// type, and its Snapshot is entirely exported plain structs, so the snapshot
// is built directly — the same thing its collector would have produced.
//
//	web       4 vCPU / 8 GB reserved, ~12 % CPU / ~20 % memory → task-size drop
//	migrator  mid-deployment                                    → refusal
func buildECSSnapshot(t *testing.T) *domain.Snapshot {
	t.Helper()
	win := kecs.Window{Start: fixtureNow.Add(-15 * 24 * time.Hour), End: fixtureNow}
	// 10-minute spacing keeps the fixture small while clearing the sizer's
	// evidence AND confidence gates: confidence composes history depth against
	// 2x MinSamples (1440) and window span against 2x MinWindow (14 days), so
	// a fixture that merely passes the minimums scores too low to propose
	// anything. Series.PeriodSeconds records the granularity honestly.
	const period = 10 * time.Minute
	const points = 2100

	web := kecs.Observation{
		Ref: domain.TargetRef{
			Domain: domain.ECSFargate, Scope: fixtureScope,
			ID: kecs.TargetID(fixtureCluster, "web"), Name: "web",
		},
		Service: kecs.ServiceRecord{
			ServiceARN:  "arn:aws:ecs:us-east-1:000000000000:service/prod/web",
			ServiceName: "web",
			ClusterARN:  "arn:aws:ecs:us-east-1:000000000000:cluster/prod",
			Status:      "ACTIVE", LaunchType: "FARGATE", PlatformVersion: "1.4.0",
			PlatformFamily: "Linux",
			TaskDefinition: "arn:aws:ecs:us-east-1:000000000000:task-definition/web:7",
			DesiredCount:   4, RunningCount: 4,
			Deployments: []kecs.Deployment{{
				ID: "ecs-svc/1", Status: kecs.DeploymentPrimary,
				TaskDefinition: "arn:aws:ecs:us-east-1:000000000000:task-definition/web:7",
				DesiredCount:   4, RunningCount: 4, RolloutState: "COMPLETED",
				CreatedAt: fixtureNow.Add(-30 * 24 * time.Hour),
				UpdatedAt: fixtureNow.Add(-30 * 24 * time.Hour),
			}},
			CreatedAt: fixtureNow.Add(-200 * 24 * time.Hour),
		},
		TaskDef: kecs.TaskDefinitionRecord{
			TaskDefinitionARN: "arn:aws:ecs:us-east-1:000000000000:task-definition/web:7",
			Family:            "web", Revision: 7, Status: "ACTIVE",
			CPU: "4096", Memory: "8192", NetworkMode: kecs.NetworkModeAWSVPC,
			RequiresCompatibilities: []string{"FARGATE"},
			RuntimePlatform: kecs.RuntimePlatform{
				CPUArchitecture: string(kecs.ArchX86), OperatingSystemFamily: string(kecs.OSLinux),
			},
			ContainerDefinitions: []kecs.ContainerDefinition{{Name: "web", MemoryReservation: 512}},
		},
		Reserved: kecs.Reservation{
			Revision: 7,
			ARN:      "arn:aws:ecs:us-east-1:000000000000:task-definition/web:7",
			Reserved: model.Resources{MilliCPU: 4000, MemoryBytes: 8 << 30},
		},
		CPUPercent: ecsSeries(kecs.MetricCPUUtilization, period, points, []float64{11, 12, 13, 12}),
		MemPercent: ecsSeries(kecs.MetricMemoryUtilization, period, points, []float64{19, 20, 21, 20}),
		Window:     win,
	}

	migrator := kecs.Observation{
		Ref: domain.TargetRef{
			Domain: domain.ECSFargate, Scope: fixtureScope,
			ID: kecs.TargetID(fixtureCluster, "migrator"), Name: "migrator",
		},
		Service: kecs.ServiceRecord{
			ServiceARN:  "arn:aws:ecs:us-east-1:000000000000:service/prod/migrator",
			ServiceName: "migrator",
			ClusterARN:  "arn:aws:ecs:us-east-1:000000000000:cluster/prod",
			Status:      "ACTIVE", LaunchType: "FARGATE", PlatformVersion: "1.4.0",
			PlatformFamily: "Linux",
			TaskDefinition: "arn:aws:ecs:us-east-1:000000000000:task-definition/migrator:3",
			DesiredCount:   2, RunningCount: 1, PendingCount: 1,
			Deployments: []kecs.Deployment{
				{
					ID: "ecs-svc/2", Status: kecs.DeploymentPrimary,
					TaskDefinition: "arn:aws:ecs:us-east-1:000000000000:task-definition/migrator:3",
					DesiredCount:   2, RunningCount: 1, PendingCount: 1,
					RolloutState: "IN_PROGRESS",
					CreatedAt:    fixtureNow.Add(-5 * time.Minute),
					UpdatedAt:    fixtureNow.Add(-time.Minute),
				},
				{
					ID: "ecs-svc/3", Status: "ACTIVE",
					TaskDefinition: "arn:aws:ecs:us-east-1:000000000000:task-definition/migrator:2",
					DesiredCount:   2, RunningCount: 1,
					CreatedAt: fixtureNow.Add(-20 * 24 * time.Hour),
				},
			},
			CreatedAt: fixtureNow.Add(-100 * 24 * time.Hour),
		},
		TaskDef: kecs.TaskDefinitionRecord{
			TaskDefinitionARN: "arn:aws:ecs:us-east-1:000000000000:task-definition/migrator:3",
			Family:            "migrator", Revision: 3, Status: "ACTIVE",
			CPU: "2048", Memory: "4096", NetworkMode: kecs.NetworkModeAWSVPC,
			RequiresCompatibilities: []string{"FARGATE"},
			RuntimePlatform: kecs.RuntimePlatform{
				CPUArchitecture: string(kecs.ArchX86), OperatingSystemFamily: string(kecs.OSLinux),
			},
		},
		Reserved: kecs.Reservation{
			Revision: 3,
			ARN:      "arn:aws:ecs:us-east-1:000000000000:task-definition/migrator:3",
			Reserved: model.Resources{MilliCPU: 2000, MemoryBytes: 4 << 30},
		},
		CPUPercent: ecsSeries(kecs.MetricCPUUtilization, period, points, []float64{5, 6, 7, 6}),
		MemPercent: ecsSeries(kecs.MetricMemoryUtilization, period, points, []float64{9, 10, 11, 10}),
		Window:     win,
	}

	native := &kecs.Snapshot{
		Domain: domain.ECSFargate, Scope: fixtureScope, Cluster: fixtureCluster,
		Timestamp: fixtureNow, Window: win,
		Services: []kecs.Observation{migrator, web},
	}
	return wrapPayload(t, domain.ECSFargate, fixtureScope, native)
}

func ecsSeries(metric string, period time.Duration, n int, values []float64) kecs.Series {
	s := kecs.Series{
		Metric: metric, PeriodSeconds: int32(period / time.Second),
		StatusCode: kecs.StatusComplete,
	}
	start := fixtureNow.Add(-time.Duration(n) * period)
	for i := 0; i < n; i++ {
		s.Timestamps = append(s.Timestamps, start.Add(time.Duration(i+1)*period))
		s.Values = append(s.Values, values[i%len(values)])
	}
	return s
}

// buildLambdaSnapshot records two Lambda functions.
//
//	tuned     measured at TWO memory settings → a claimable, measured saving
//	untuned   measured at one setting only    → the single-memory-point refusal
//
// The second is the fleet-wide default in reality, and the honest output for
// it is a refusal plus a power-tuning trial, not an estimate.
func buildLambdaSnapshot(t *testing.T) *domain.Snapshot {
	t.Helper()
	win := klambda.Window{Start: fixtureNow.Add(-14 * 24 * time.Hour), End: fixtureNow}
	// The Invocations metric is sized to match the REPORT lines that survived
	// parsing, because their ratio IS the report-coverage confidence factor: a
	// fixture with two thousand invocations and two hundred log lines would
	// fail on evidence coverage rather than on the arithmetic under test.

	tuned := klambda.Target{
		Ref: domain.TargetRef{
			Domain: domain.Lambda, Scope: fixtureScope,
			ID:   "arn:aws:lambda:us-east-1:000000000000:function:thumbnailer",
			Name: "thumbnailer",
		},
		Function: klambda.Function{
			ARN:          "arn:aws:lambda:us-east-1:000000000000:function:thumbnailer",
			Name:         "thumbnailer",
			MemoryMB:     1024,
			Architecture: klambda.ArchX86,
			PackageType:  klambda.PackageZip,
			Runtime:      "python3.12",
		},
	}
	// 1024 MB is what it runs on today, measured; 512 MB is a setting it ran
	// on earlier in the window (a retune, a rollback, a deliberate trial).
	// The duration at 512 MB is only ~1.6× longer, so half the memory is a
	// real, MEASURED reduction in GB-seconds.
	tuned.Reports = append(tuned.Reports,
		parseSynthetic(t, "thumb-hi", fixtureNow.Add(-7*24*time.Hour), 7*24*time.Hour,
			600, 42.0, 1024, 300)...)
	tuned.Reports = append(tuned.Reports,
		parseSynthetic(t, "thumb-lo", fixtureNow.Add(-14*24*time.Hour), 7*24*time.Hour,
			600, 68.0, 512, 300)...)
	tuned.Series = append(tuned.Series, klambda.Series{
		Metric: klambda.MetricInvocations,
		Points: klambda.SyntheticMetric(win.Start, time.Hour, 336, 4.0),
	})

	untuned := klambda.Target{
		Ref: domain.TargetRef{
			Domain: domain.Lambda, Scope: fixtureScope,
			ID:   "arn:aws:lambda:us-east-1:000000000000:function:webhook",
			Name: "webhook",
		},
		Function: klambda.Function{
			ARN:          "arn:aws:lambda:us-east-1:000000000000:function:webhook",
			Name:         "webhook",
			MemoryMB:     512,
			Architecture: klambda.ArchX86,
			PackageType:  klambda.PackageZip,
			Runtime:      "nodejs20.x",
		},
	}
	untuned.Reports = parseSynthetic(t, "hook", win.Start, 14*24*time.Hour,
		1100, 25.0, 512, 74)
	untuned.Series = append(untuned.Series, klambda.Series{
		Metric: klambda.MetricInvocations,
		Points: klambda.SyntheticMetric(win.Start, time.Hour, 336, 3.5),
	})

	native := &klambda.Snapshot{
		Domain: domain.Lambda, Scope: fixtureScope, Region: fixtureRegion,
		Timestamp: fixtureNow, Window: win,
		Targets: []klambda.Target{tuned, untuned},
	}
	klambda.SortTargets(native.Targets)
	return wrapPayload(t, domain.Lambda, fixtureScope, native)
}

// parseSynthetic builds REPORT log lines and parses them back, so the fixture
// carries records that went through the real parser rather than structs a test
// filled in by hand.
func parseSynthetic(t *testing.T, prefix string, start time.Time, span time.Duration,
	n int, billedMS float64, memoryMB, maxUsedMB int64) []klambda.ReportRecord {
	t.Helper()
	// coldEvery = 0 ⇒ every invocation is warm. Cold records never contribute
	// to warm duration statistics, and a fixture that mixed the two at
	// different memory settings would invent a cost difference memory had
	// nothing to do with.
	events := klambda.SyntheticReports(prefix, start, span, n, memoryMB, maxUsedMB, billedMS, 0, 0)
	recs, drops := klambda.ParseEvents(events)
	if len(drops) > 0 {
		t.Fatalf("synthetic REPORT lines were dropped: %v", drops)
	}
	if len(recs) != n {
		t.Fatalf("parsed %d records, want %d", len(recs), n)
	}
	return recs
}

// buildInventory is the commitment position that makes §7 trap 1 concrete: a
// standard m5.2xlarge Reserved Instance covering exactly the instance the EC2
// sizer wants to shrink.
//
// The RI bills whether or not usage absorbs it. Downsizing that instance to
// m5.large leaves most of the reservation stranded, so the *bill* barely moves
// — or moves the wrong way — while the list-price delta looks like $210/month.
// That is the number a naive optimizer reports and this one refuses to.
func buildInventory() *kcommit.Inventory {
	return &kcommit.Inventory{
		FetchedAt: fixtureNow.Add(-24 * time.Hour),
		RIs: []kcommit.ReservedInstance{{
			ID: "ri-fixture-m5", Count: 1, InstanceType: "m5.2xlarge",
			Region: fixtureRegion, Platform: kcommit.PlatformLinux,
			OfferingClass: "standard", EffectiveHourlyUSD: 0.242,
			Expires: fixtureNow.Add(300 * 24 * time.Hour),
		}},
	}
}

// buildClusterSnapshot is a minimal EKS-on-Fargate cluster: one Fargate pod
// sitting exactly on the §4.1.1 overhead cliff. It requests 1 vCPU / 8 GiB and
// AWS bills it 2 vCPU / 9 GB, because Fargate adds 256 MiB of Kubernetes
// overhead before rounding up to a tier — so 8 GiB of request costs a whole
// extra vCPU.
//
// It is the model.ClusterSnapshot format `kilter analyze --dump-snapshot` and
// `kilter simulate` already use, so this fixture doubles as a check that the
// k8s-fargate domain reads the collector's real output.
func buildClusterSnapshot() *model.ClusterSnapshot {
	ref := model.WorkloadRef{Kind: model.KindDeployment, Namespace: "default", Name: "api"}
	snap := &model.ClusterSnapshot{
		ClusterID: "prod-eks",
		Timestamp: fixtureNow,
		Nodes: []model.NodeSpec{{
			Name:      "fargate-ip-10-0-1-5.ec2.internal",
			Labels:    map[string]string{model.LabelComputeType: "fargate"},
			ManagedBy: model.ManagedByFargate,
			// A Fargate VM reports an absurd shell capacity. §7 trap 7: fed to
			// binpack it produces nonsense; pricing.SplitFargate is what keeps
			// it out, and this fixture is the reason to prove it.
			Capacity:    model.Resources{MilliCPU: 96000, MemoryBytes: 384 << 30},
			Allocatable: model.Resources{MilliCPU: 96000, MemoryBytes: 384 << 30},
			Ready:       true,
			Provider:    "aws", Region: fixtureRegion, Zone: fixtureRegion + "a",
		}},
		Pods: []model.PodSpec{{
			UID: "pod-fargate-1", Name: "api-0", Namespace: "default",
			Workload: ref, NodeName: "fargate-ip-10-0-1-5.ec2.internal",
			Phase:     "Running",
			CreatedAt: fixtureNow.Add(-30 * 24 * time.Hour),
			Containers: []model.ContainerSpec{{
				Name:     "api",
				Requests: model.Resources{MilliCPU: 1000, MemoryBytes: 8 << 30},
			}},
			// The AWS-stamped billed capacity. It outranks any computed
			// estimate, and it is what the quantizer is validated against.
			ProvisionedCapacity: model.Resources{MilliCPU: 2000, MemoryBytes: 9 * 1000 * 1000 * 1000},
		}},
		Workloads: []model.WorkloadInfo{{Ref: ref, Replicas: 1, Ready: 1}},
	}
	// Three days of one-minute samples: a steady 300 mCPU and a 7 GiB memory
	// peak, comfortably under the 8 GiB request. That is what makes the
	// boundary shave arithmetically interesting — dropping the request by
	// 256 MiB lands the pod a whole vCPU cheaper.
	key := model.ContainerKey{Workload: ref, Container: "api"}
	const samples = 288 // three days at 15-minute spacing
	const spacing = 15 * time.Minute
	start := fixtureNow.Add(-time.Duration(samples) * spacing)
	mem := []int64{6_900_000_000, 7_000_000_000, 6_950_000_000, 7_010_000_000}
	for i := 0; i < samples; i++ {
		snap.Usage = append(snap.Usage, model.Usage{
			Key: key, PodUID: "pod-fargate-1",
			Timestamp:     start.Add(time.Duration(i+1) * spacing),
			MilliCPU:      300,
			MemoryBytes:   mem[i%len(mem)],
			WindowSeconds: int32(spacing / time.Second),
		})
	}
	return snap
}

// wrapPayload puts a domain-native snapshot into the generic envelope's opaque
// Payload — the field pkg/lambda/FINDINGS.md §8 asked a later unit to add.
func wrapPayload(t *testing.T, k domain.Kind, scope string, native any) *domain.Snapshot {
	t.Helper()
	raw, err := json.Marshal(native)
	if err != nil {
		t.Fatalf("marshal %s payload: %v", k, err)
	}
	return &domain.Snapshot{
		Domain: k, Scope: scope, Timestamp: fixtureNow, Payload: raw,
	}
}

// readFixture is the test-side counterpart: it loads a committed fixture the
// same way the CLI does.
func readFixture(t *testing.T, name string) string {
	t.Helper()
	path := fixturePath(name)
	if _, err := os.Stat(path); err != nil {
		t.Skipf("fixture %s is missing: %v (run with -update-fixtures)", path, err)
	}
	return path
}

func mustJSON(t *testing.T, v any) string {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

var _ = fmt.Sprintf
