apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token
  labels: {{- include "kilter.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ include "kilter.token" . | quote }}
